spring:
  profiles:
    # 默认的类型
    active: dev
  application:
    name: ${spring.profiles.active}
  cloud:
    nacos:
      discovery:
        # 指定nacos的命名空间
        namespace: ${spring.cloud.nacos.config.namespace}
      config:
        file-extension: yaml
        # nacos地址
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace:  ${spring.cloud.nacos.discovery.namespace}
        extension-configs:
          # metrics config
          - dataId: global-config.yml
            group: GLOBAL_GROUP
            refresh: true
            # email config
          - dataId: mail-config.yml
            group: GLOBAL_GROUP
            refresh: true

